# Generated by Django 4.2.5 on 2023-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_alter_students_options_remove_students_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='avatarka',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
